name = "khata"
license = "MIT"
licenselink = "https://github.com/darshanbaral/khata/blob/master/LICENSE"
description = "Documentation theme for Hugo"
homepage = "https://github.com/darshanbaral/khata"
tags = ["documentation", "simple"]
features = ["documentation", "bootstrap", "responsive"]
min_version = "0.55"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
