baseURL = "/"
title = "My Blog Site"
theme = "khata"
languageCode = "en-us"
copyright = "2019. First Last"
pluralizelisttitles = false
disableKinds = ["taxonomy"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  dateFormat = "2006-01-02"

[params.author] 
  name = "McFirst Last, A.B., X.Y"
  profilephoto = "homePageImage.jpg"
  title = "Title"
  subtitle = "City Name, ST"
  about = '''
  **Lorem Ipsum is simply dummy text of the printing and typesetting industry**. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into *electronic typesetting*, remaining essentially unchanged.
'''

[[params.social]]
  name = "Twitter"
  link = "#"
  iconclass= "bi bi-twitter-x"

[[params.social]]
  name = "LinkedIn"
  link = "#"
  iconclass= "bi bi-linkedin"

[[params.social]]
  name = "Email"
  link = "mailto:username@domain.com"
  iconclass= "bi bi-envelope-at-fill"
